categories:
  - type: "pre-exclude"
    when:
      label: "skip-changelog"
  - title: ":boom: Breaking Changes"
    when:
      label: "breaking"
  - title: ":rocket: Features"
    when:
      label: "enhancement"
  - title: ":fire: Removals and Deprecations"
    when:
      label: "removal"
  - title: ":beetle: Fixes"
    when:
      label: "bug"
  - title: ":racehorse: Performance"
    when:
      label: "performance"
  - title: ":rotating_light: Testing"
    when:
      label: "testing"
  - title: ":construction_worker: Continuous Integration"
    when:
      label: "ci"
  - title: ":books: Documentation"
    when:
      label: "documentation"
  - title: ":hammer: Refactoring"
    when:
      label: "refactoring"
  - title: ":lipstick: Style"
    when:
      label: "style"
  - title: ":package: Dependencies"
    when:
      label: "dependencies"
template: |
  ## Changes

  $CHANGES
