name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  tests:
    name: ${{ matrix.session }} ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.12", os: "ubuntu-latest", session: "pre-commit" }
          - { python: "3.12", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.13", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.12", os: "ubuntu-latest", session: "tests" }
          - { python: "3.13", os: "ubuntu-latest", session: "tests" }
          - { python: "3.14", os: "ubuntu-latest", session: "tests" }
          - { python: "3.13", os: "windows-latest", session: "tests" }
          - { python: "3.13", os: "macos-latest", session: "tests" }
          - { python: "3.12", os: "ubuntu-latest", session: "typeguard" }
          - { python: "3.12", os: "ubuntu-latest", session: "xdoctest" }
          - { python: "3.12", os: "ubuntu-latest", session: "docs-build" }

    env:
      NOXSESSION: ${{ matrix.session }}
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
      INTEGRATION_TESTS: FALSE

    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get uv version from constraints
        id: uv-version
        shell: pwsh
        run: |
          $UV_VERSION = (Get-Content .github/workflows/constraints.txt | Where-Object { $_ -match '^uv==' } | ForEach-Object { ($_ -split '==')[1] })
          echo "version=$UV_VERSION" >> $env:GITHUB_OUTPUT

      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: true
          version: ${{ steps.uv-version.outputs.version }}
          python-version: ${{ matrix.python }}

      - name: Compute pre-commit cache key
        if: matrix.session == 'pre-commit'
        id: pre-commit-cache
        shell: python
        run: |
          import hashlib
          import subprocess
          import sys

          python = "py{}.{}".format(*sys.version_info[:2])
          payload = sys.version.encode() + sys.executable.encode()
          digest = hashlib.sha256(payload).hexdigest()
          result = "${{ runner.os }}-{}-{}-pre-commit".format(python, digest[:8])
          cmd = f'echo "result={result}" >> $GITHUB_OUTPUT'
          subprocess.run(cmd, shell=True)

      - name: Restore pre-commit cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: matrix.session == 'pre-commit'
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.pre-commit-cache.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ steps.pre-commit-cache.outputs.result }}-

      - name: Run Nox
        run: |
          uvx --constraints "${{ github.workspace }}/.github/workflows/constraints.txt" nox --python=${{ matrix.python }}

      - name: Upload documentation
        if: matrix.session == 'docs-build'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docs
          path: docs/_build

  integration_tests:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.12" }
          - { python: "3.13" }
          - { python: "3.14" }
    env:
      FORCE_COLOR: "1"
      WHODAT_SERVICE_URL: "https://whodat-service.test.ssb.no"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093" # v3.0.0
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.INTEGRATION_TEST_SA_EMAIL }}
        token_format: "access_token"
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db' # v3.0.1
      with:
        version: '>= 363.0.0'
    - name: Generate, mask, and output Google ID token as a secret
      id: get-id-token
      env:
        PRIVILEGED_SERVICE_ACCOUNT: ${{ secrets.INTEGRATION_TEST_PRIV_SA_EMAIL }}
      run: |
        # REQUIRED TO KEEP GH ACTIONS FOR LOGGING THE ID TOKEN
        # SEE: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-masking-a-generated-output-within-a-single-job
        whodat_service_auth_token="$(gcloud auth print-identity-token --impersonate-service-account=$PRIVILEGED_SERVICE_ACCOUNT --audiences=$WHODAT_SERVICE_URL --include-email)"
        echo "::add-mask::$whodat_service_auth_token"
        echo "WHODAT_SERVICE_AUTH_TOKEN=$whodat_service_auth_token" >> "$GITHUB_OUTPUT"

    - name: Get uv version from constraints
      id: uv-version
      shell: pwsh
      run: |
        $UV_VERSION = (Get-Content .github/workflows/constraints.txt | Where-Object { $_ -match '^uv==' } | ForEach-Object { ($_ -split '==')[1] })
        echo "version=$UV_VERSION" >> $env:GITHUB_OUTPUT

    - name: Install uv
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      with:
        enable-cache: true
        version: ${{ steps.uv-version.outputs.version }}
        python-version: ${{ matrix.python }}

    - name: Run Nox
      env:
        WHODAT_SERVICE_AUTH_TOKEN: ${{ steps.get-id-token.outputs.WHODAT_SERVICE_AUTH_TOKEN }}
      run: |
        uvx --constraints "${{ github.workspace }}/.github/workflows/constraints.txt" nox --python=${{ matrix.python }} --session tests -- tests/integration
